version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: tugasku_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1812nasya
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:1812nasya@db:5432/tugasku_db
      JWT_SECRET: your-super-secret-jwt-key
      ENVIRONMENT: production
    ports:
      - "6543:6543"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6543/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
